# PPI(Using package)
```{r}
library(STRINGdb)
string_db <- STRINGdb$new(version="11", species=9606,
                           score_threshold=200, input_directory="")
```

# Prerequisites
```{r}
library(igraph)
library(ggplot2)
library(RColorBrewer)
```

# Data manipulation
```{r}
###
string_table <- greenyellow_string_interactions_short # modify here
###
# string_table_high <- string_table[string_table$combined_score > 0.7,]
# ggplot(string_table_high, aes(x=combined_score))+
#  geom_density()
# string_table <- string_table_high

nodes <- unique(c(string_table$node1,string_table$node2))
edges <- string_table[,c("node1","node2","combined_score")]
colnames(edges)[3] <- "weight" 
net <- graph_from_data_frame(d=edges,vertices=nodes, directed = F)
# net <- simplify(net)

V(net)$strength <- strength(net,vids = V(net), mode = "out", loops = T)
V(net)$bettername <- V(net)$name
V(net)$bettername[V(net)$strength < max(V(net)$strength/2)] <- NA
# plot(net, vertex.size = 5, edge.arrow.size=.4, vertex.label=V(net)$name)
# net_layout <- layout_with_dh(net) # don't try dh
# net_communities <- cluster_fast_greedy(net)

# V(net)$membership <- membership(net_communities)
colrs <- c("white","greenyellow") # modify here
palette1 <- colorRampPalette(colrs)
V(net)$color <- palette1(20)[12]
V(net)$color[!is.na(V(net)$bettername)] <- "greenyellow" # modify here
```

# Layout settings
```{r}
x_coord <- c()
y_coord <- c()
max_str <- max(V(net)$strength) 
better_degr <- seq(from=18, to=360, length.out=length(na.omit(V(net)$bettername)))
j=1

for(i in 1:vcount(net)){
  if ( V(net)$strength[i] >  max_str/2 ) {
#    rad <- 1.3-(V(net)$strength[i]/max(V(net)$strength))^3
    rad <- 0.8
    degr <- 3.14159 * (better_degr[j]/180)
    j <- j + 1
  } else {
    rad <- 1.8-(V(net)$strength[i]/max(V(net)$strength))^1.5
    degr <- sample(1:720,1)
    degr <- 3.14159 * (degr/360)
  }
  
  x_coord <- append(x_coord, rad*cos(degr))
  y_coord <- append(y_coord, rad*sin(degr))
}
net_layout <- cbind(x_coord, y_coord)
E(net)$weight[E(net)$weight < 0.9] <- 0

# net_layout <- layout_with_kk(net, weights = E(net)$weight*2)
plot(net, 
     edge.width = E(net)$weight,  
     vertex.size = (V(net)$strength)/1.2, 
     vertex.label.cex = V(net)$strength/40,
     vertex.label.color = "black",
     edge.arrow.size=.4, 
     vertex.label=V(net)$bettername,
     layout=net_layout)

ggplot(V(net)$strength)+
  geom_histogram()
```

