# Prerequisites
```{r}
library(WGCNA)
# Workflow: 
# datExpr, datTraits 
# | sft (soft threshold for scale-free topology)
# - sft plot
# | net
# - module colors plot
# | datExpr_tree
# | MEs (Module eigengenes)
```


# Reading data
```{r}
datTraits <- MetaData_all_test
WGCNA_matrix <- as.matrix(SeriesMatrix_clean_test)
WGCNA_matrix_5000 <- t(WGCNA_matrix[order(apply(WGCNA_matrix,1,mad),decreasing = T),])
WGCNA_matrix_5000 <- WGCNA_matrix_5000[,1:5000]
datExpr <- WGCNA_matrix_5000

# datTraits <- metadata_subset_mid
powers <- c(seq(1, 10, by = 1), seq(12, 20, by = 2))
# Pick soft-threshold, `powerVector` is default
sft = pickSoftThreshold(datExpr, power = powers, verbose = 5)
```

# Plot the sft results
```{r}
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3]) * sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
```

# Gene modules
```{r}
net = blockwiseModules(
  datExpr,
  power = sft$powerEstimate,
  maxBlockSize = 6000,
  TOMType = "unsigned", minModuleSize = 30,
  reassignThreshold = 0, mergeCutHeight = 0.25,
  numericLabels = TRUE, pamRespectsDendro = FALSE,
  saveTOMs = F,
  verbose = 3)  
table(net$colors)
mergedColors <- labels2colors(net$colors)
# Plot the modules
plotDendroAndColors(net$dendrograms[[1]], mergedColors[net$blockGenes[[1]]], # Last time
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)

nGenes <- ncol(datExpr)
nSamples <- nrow(datExpr)
```

# Hierarchical tree
```{r}
datExpr_tree <- hclust(dist(datExpr), method = "average")
par(mar = c(0,5,2,0))
plot(datExpr_tree, main = "Sample clustering", sub="", xlab="", cex.lab = 2, 
     cex.axis = 1, cex.main = 1,cex.lab=1)
sample_colors <- numbers2colors(as.numeric(factor(datTraits$group)), 
                                colors = c("#61d36b","#f1978d","#8db6f9"),signed = FALSE)
par(mar = c(1,4,3,1),cex=0.8)
plotDendroAndColors(datExpr_tree, sample_colors,
#                    colors = c("#61d36b","#f1978d","#8db6f9"),
                    groupLabels = colnames(sample),
                    cex.dendroLabels = 0.8,
                    marAll = c(1, 4, 3, 1),
                    cex.rowText = 0.01,
                    main = "Sample dendrogram")
```

# Modules & Traits
```{r}
design=model.matrix(~0+ datTraits$group)
colnames(design)=levels(factor(datTraits$group))
moduleColors <- labels2colors(net$colors)
# Recalculate MEs with color labels
MEs0 = moduleEigengenes(datExpr, moduleColors)$eigengenes # ??
MEs = orderMEs(MEs0); ##不同颜色的模块的ME值矩阵(样本vs模块)
moduleTraitCor = cor(MEs, design , use = "p");
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nSamples)

sizeGrWindow(10,6)
# Will display correlations and their p-values
textMatrix = paste(signif(moduleTraitCor, 2), "\n(",
                   signif(moduleTraitPvalue, 1), ")", sep = "");
dim(textMatrix) = dim(moduleTraitCor)
par(mar = c(6, 8.5, 3, 3));
# Display the correlation values within a heatmap plot
labeledHeatmap(Matrix = moduleTraitCor,
               xLabels = colnames(design),
               yLabels = names(MEs),
               ySymbols = names(MEs),
               colorLabels = FALSE,
               colors = blueWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.7,
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
```

# Correlation chart
```{r}
module = "greenyellow" # modify here
column = match(module, modNames);
moduleGenes = moduleColors==module;
sizeGrWindow(7, 7);
par(mfrow = c(1,1));
verboseScatterplot(abs(geneModuleMembership[moduleGenes, column]),
                   abs(geneTraitSignificance[moduleGenes, 1]),
                   xlab = paste("Module Membership in", module, "module"),
                   ylab = "Gene significance for IPAH", # Modify here
                   main = paste("Module membership vs. gene significance\n"),
                   cex.main = 1.2, cex.lab = 1.2, cex.axis = 1.2, col = module)
```


# Visualizing network
```{r}
nGenes = ncol(datExpr)
nSamples = nrow(datExpr)
geneTree = net$dendrograms[[1]]; 
dissTOM = 1-TOMsimilarityFromExpr(datExpr, power = 6); 
plotTOM = dissTOM^7; 
diag(plotTOM) = NA; 
#TOMplot(plotTOM, geneTree, moduleColors, main = "Network heatmap plot, all genes")


## Randomly selected part of the genes
nSelect = 1000
# For reproducibility, we set the random seed
set.seed(42)
select = sample(nGenes, size = nSelect)
selectTOM = dissTOM[select, select]
```

# Recalculating module eigengenes
```{r}
MEs = moduleEigengenes(datExpr, moduleColors)$eigengenes

CTDPAH = as.data.frame(design[,2]);
names(CTDPAH) = "CTD-PAH"
# Add the weight to existing module eigengenes
MET = orderMEs(cbind(MEs, CTDPAH))
# Plot the relationships among the eigengenes and the trait
# Dendrogram & Heatmap
plotEigengeneNetworks(MET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle = 90)
```

# Output genes from a module
```{r}
# Output genes from a module
module = "turquoise"
# Select module probes
probes = colnames(datExpr) ## 我们例子里面的probe就是基因名
inModule = (moduleColors==module)
modProbes = probes[inModule]
write.table(modProbes, file = "turquoise.txt", quote = F, row.names = F, col.names = F)

turquoise_module <- modProbes

# Recalculate topological overlap
TOM = TOMsimilarityFromExpr(datExpr, power = 6); 
# Select module

# Select the corresponding Topological Overlap
modTOM = TOM[inModule, inModule]
# Only the relationship between the genes in the module
dimnames(modTOM) = list(modProbes, modProbes)


cyt = exportNetworkToCytoscape(
  modTOM,
  edgeFile = paste("CytIN-5groups-edges-", paste(module, collapse="-"), ".txt", sep=""),
  nodeFile = paste("CytIN-5groups-nodes-", paste(module, collapse="-"), ".txt", sep=""),
  weighted = TRUE,
  threshold = 0.02,
  nodeNames = modProbes, 
  nodeAttr = moduleColors[inModule]
)
```

# Hub gene
```{r}
# By kME 
datKME <- signedKME(datExpr, MEs, outputColumnName = "kME_MM.")
# write.csv(datKME, "kME_MM.csv")
Filter_gene <- abs(datKME$kME_MM.salmon) > 0.75
table(Filter_gene)
hubgene_salmon_CHD <- dimnames(data.frame(datExpr))[[2]][Filter_gene]

# By Cytoscape weight
nTop <- 30
IMConn <- softConnectivity(datExpr[,modProbes])
top = (rank(-IMConn) <= nTop)
cyt = exportNetworkToCytoscape(modTOM[top, top],
                               edgeFile = paste("CytoscapeInput-edges-", paste(module, collapse="-"), "_top30.txt", sep=""), 
                               nodeFile = paste("CytoscapeInput-nodes-", paste(module,  collapse="-"), ".txt", sep=""),
                               weighted = TRUE, 
                               nodeNames = modProbes, nodeAttr = moduleColors[inModule])

# To entrez and kegg

modProbes_entrez <- bitr(modProbes_salmon, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)
KEGG_salmon_CHD <- enrichKEGG(modProbes_entrez$ENTREZID)

ggplot(data = KEGG_greenyellow@result[1:10,], aes(x=Count,y=Description,fill = p.adjust))+
  geom_bar(stat = "identity",width = 0.7)+
  scale_fill_gradient(low = "red",high = "blue")+
  labs(title = "KEGG Pathways Enrichment",
       x = "Gene Counts",
       y = "KEGG Pathways")+
  theme_bw()


# 
datTraitsnew <- datTraits
datTraitsnew$GATA2 <- datExpr[,"GATA2"]
```

